<?xml version="1.0"?>
<robot name="fratomo_base_macro" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!--All units in m-kg-s-radians unit system -->
  <xacro:property name="M_PI" value="3.1415926535897931" />
  <xacro:property name="M_PI_2" value="1.570796327" />
  <xacro:property name="DEG_TO_RAD" value="0.017453293" />

	<!--Material Definition-->  
	<material name="Black">
	  <color rgba="0.0 0.0 0.0 1.0"/>
	</material>

  <material name="Red">
  	<color rgba="0.8 0.0 0.0 1.0"/>
  </material>

  <material name="White">
    <color rgba="1.0 1.0 1.0 1.0"/>
  </material>

  <material name="Blue">
    <color rgba="0.0 0.0 0.8 1.0"/>
  </material>

  <!-- Base properties -->
	<xacro:property name="base_height" value="0.25" /> 
  <xacro:property name="base_radius" value="0.113" /> 
  <xacro:property name="base_mass" value="5" />
  <xacro:property name="wheel_mass" value="2.5" />
  <xacro:property name="wheel_radius" value="0.0375" /> 

  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertia  ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
              iyy="${m*(3*r*r+h*h)/12}" iyz = "0"
              izz="${m*r*r/2}" /> 
  </xacro:macro>

  <!-- WHOLE BASE MACRO-->
  <xacro:macro name="fratomo_base" > <!--fb : front, back ; lr: left, right -->
   
      <!--Actual body/chassis of the robot-->
    <link name="base_link">
      <inertial>
          <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
        <mass value="${base_mass}" />
        <origin xyz="0 0 0" />
        <cylinder_inertia  m="${base_mass}" r="${base_radius}" h="${base_height}" />
      </inertial>    
      <visual> 
        <geometry>
          <mesh filename="package://fratomo_pro_description/meshes/base.stl" scale="0.001 0.001 0.001 "/>
        </geometry>
        <material name="White"/>
        <origin rpy="0 0 1.57075" xyz="0 0 0"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0 " />
        <geometry>
          <mesh filename="package://fratomo_pro_description/meshes/base.stl" scale="0.001 0.001 0.001 "/>
        </geometry>
        <origin rpy="0 0 1.57075" xyz="0 0 0"/>
      </collision>     
    </link>

    <link name="caster_front_link">
      <visual> 
        <geometry>
          <mesh filename="package://fratomo_pro_description/meshes/casterWheel.stl" scale="0.001 0.001 0.001 "/>
        </geometry>
        <material name="Black"/>
        <origin rpy="0 0 0" xyz="0 0 0"/>
      </visual>
      <collision> 
        <geometry>
          <mesh filename="package://fratomo_pro_description/meshes/casterWheel.stl" scale="0.001 0.001 0.001 "/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
      </collision>
      <inertial>
        <mass value="0.5"/>
        <origin xyz="0 0 0" />
          <inertia  ixx="0.001" ixy="0.0" ixz="0.0"
                    iyy="0.001" iyz="0.0" 
                    izz="0.001" />
      </inertial>
    </link>

    <link name="caster_rear_link">
      <visual> 
        <geometry>
          <mesh filename="package://fratomo_pro_description/meshes/casterWheel.stl" scale="0.001 0.001 0.001 "/>
        </geometry>
        <material name="Black"/>
        <origin rpy="0 0 0" xyz="0 0 0"/>
      </visual>
      <collision> 
        <geometry>
          <mesh filename="package://fratomo_pro_description/meshes/casterWheel.stl" scale="0.001 0.001 0.001 "/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
      </collision>
      <inertial>
        <mass value="0.5"/>
        <origin xyz="0 0 0" />
          <inertia  ixx="0.001" ixy="0.0" ixz="0.0"
                    iyy="0.001" iyz="0.0" 
                    izz="0.001" />
      </inertial>
    </link>

    <link name="left_wheel_link">
      <visual> 
        <geometry>
          <mesh filename="package://fratomo_pro_description/meshes/wheel.stl" scale="0.001 0.001 0.001 "/>
        </geometry>
        <material name="Black"/>
        <origin rpy="0 0 0" xyz="0 0 0"/>
      </visual>
      <collision> 
        <geometry>
          <mesh filename="package://fratomo_pro_description/meshes/wheel.stl" scale="0.001 0.001 0.001 "/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
      </collision>
      <inertial>
        <mass value="${wheel_mass}" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0" 
               izz="0.001" />
      </inertial>
    </link>

    <link name="right_wheel_link">
      <visual> 
        <geometry>
          <mesh filename="package://fratomo_pro_description/meshes/wheel.stl" scale="0.001 0.001 0.001 "/>
        </geometry>
        <material name="Black"/>
        <origin rpy="0 0 0" xyz="0 0 0"/>
      </visual>
      <collision> 
        <geometry>
          <mesh filename="package://fratomo_pro_description/meshes/wheel.stl" scale="0.001 0.001 0.001 "/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
      </collision>
      <inertial>
        <mass value="${wheel_mass}" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0" 
               izz="0.001" />
      </inertial>
    </link>

    <joint name="caster_front_joint" type="fixed" >
      <parent link="base_link" />
      <child link="caster_front_link" />
       <origin rpy="0 0 0" xyz="0.1 0 0.002"/>
    </joint>

     <joint name="caster_frear_joint" type="fixed" >
      <parent link="base_link" />
      <child link="caster_rear_link" />
       <origin rpy="0 0 0" xyz="-0.1 0 0.002"/>
    </joint>
    
    <joint name="left_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="left_wheel_link"/>
      <origin rpy="${M_PI_2} 0 0" xyz="0 0.113 0.023"/>
      <axis xyz="0 0 -1" rpy="0 0 0" />
      <limit effort="100" velocity="100"/>
      <joint_properties damping="0.5" friction="0.01"/>
    </joint>

    <joint name="right_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="right_wheel_link"/>
      <origin rpy="${-M_PI_2} 0 0" xyz="0 -0.113 0.023"/>
      <axis xyz="0 0 1" rpy="0 0 0" />
      <limit effort="100" velocity="100"/>
      <joint_properties damping="0.5" friction="0.01"/>
    </joint>

    <gazebo reference="left_wheel_link">
      <mu1 value="1.0"/>
      <mu2 value="1.0"/>
      <kp  value="1000000.0" />
      <kd  value="1.0" />
      <fdir1 value="1 0 0"/>
      <material>Gazebo/Black</material>
      <turnGravityOff>false</turnGravityOff>
    </gazebo>

     <gazebo reference="right_wheel_link">
      <mu1 value="1.0"/>
      <mu2 value="1.0"/>
      <kp  value="1000000.0" />
      <kd  value="1.0" />
      <fdir1 value="1 0 0"/>
      <material>Gazebo/Black</material>
      <turnGravityOff>false</turnGravityOff>
    </gazebo>


    <gazebo reference="caster_rear_link">
      <material>Gazebo/Grey</material>
    </gazebo>

    <gazebo reference="caster_front_link">
      <material>Gazebo/Grey</material>
    </gazebo>

    
    <!-- Transmission is important to link the joints and the controller -->
    <transmission name="left_wheel_joint_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="left_wheel_joint" />
      <actuator name="left_wheel_joint_motor">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>

    <transmission name="right_wheel_joint_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="right_wheel_joint" />
      <actuator name="right_wheel_joint_motor">
        <hardwareInterface>EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>

     <!-- Differential drive controller  -->
  <gazebo>
    <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
      <legacyMode>true</legacyMode>
      <rosDebugLevel>Debug</rosDebugLevel>
      <publishWheelTF>true</publishWheelTF>
      <robotNamespace>/</robotNamespace>
      <publishTf>1</publishTf>
      <publishWheelJointState>true</publishWheelJointState>
      <alwaysOn>true</alwaysOn>
      <updateRate>100.0</updateRate>
      <leftJoint>left_wheel_joint</leftJoint>
      <rightJoint>right_wheel_joint</rightJoint>
      <wheelSeparation>${2*base_radius}</wheelSeparation>
      <wheelDiameter>${2*wheel_radius}</wheelDiameter>
      <broadcastTF>1</broadcastTF>
      <wheelTorque>30</wheelTorque>
      <wheelAcceleration>1.8</wheelAcceleration>
      <commandTopic>cmd_vel</commandTopic>
      <odometryFrame>odom</odometryFrame> 
      <odometryTopic>odom</odometryTopic> 
      <robotBaseFrame>base_link</robotBaseFrame>
    </plugin>
  </gazebo> 



   </xacro:macro>
</robot>

